version: '3'
services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nest-bank-app
    ports: 
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis
  db:
    build: .docker/postgres
    container_name: nest-bank-db
    restart: always
    tty: true
    volumes: 
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest
  redis:
    image: redis:6.2.6-alpine3.14